FROM nvidia/cuda:8.0-devel-ubuntu16.04

ARG USER_NAME
ARG USER_PASSWORD
ARG USER_ID
ARG USER_GID

RUN apt-get update
RUN apt install sudo
RUN useradd -ms /bin/bash $USER_NAME
RUN usermod -aG sudo $USER_NAME
RUN yes $USER_PASSWORD | passwd $USER_NAME

# set uid and gid to match those outside the container
RUN usermod -u $USER_ID $USER_NAME
RUN groupmod -g $USER_GID $USER_NAME

WORKDIR /home/$USER_NAME
# require no sudo pw in docker
RUN echo $USER_PASSWORD | sudo -S bash -c 'echo "'$USER_NAME' ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/docker-user' && printf "\n"

COPY spartan /home/$USER_NAME/spartan
COPY iiwa-tools /home/$USER_NAME/iiwa-tools

RUN yes "Y" | /home/$USER_NAME/spartan/setup/docker/install_dependencies.sh
RUN yes "Y" | /home/$USER_NAME/spartan/setup/ubuntu/16.04/install_prereqs.sh
RUN yes "Y" | /home/$USER_NAME/spartan/drake/setup/ubuntu/16.04/install_prereqs.sh
RUN yes "Y" | apt install ccache iptables

# build elastic fusion
#COPY ./setup/docker/install_elasticfusion.sh /tmp/install_elasticfusion.sh
#RUN yes "Y" | /tmp/install_elasticfusion.sh
#ENV ELASTIC_FUSION_EXECUTABLE=/home/$USER_NAME/ElasticFusion/install/bin/ElasticFusion

# set the terminator inside the docker container to be a different color
#RUN mkdir -p .config/terminator
#COPY ./setup/docker/terminator_config .config/terminator/config
#RUN chown $USER_NAME:$USER_NAME -R .config

RUN chown $USER_ID:$USER_GID -R /home/$USER_NAME

ENTRYPOINT bash -c "source ~/spartan/setup/docker/entrypoint.sh && /bin/bash"
