FROM nvidia/cuda:8.0-devel-ubuntu16.04

ARG USER_NAME
ARG USER_PASSWORD
ARG USER_ID
ARG USER_GID

RUN apt-get update
RUN apt install sudo
RUN useradd -ms /bin/bash $USER_NAME
RUN usermod -aG sudo $USER_NAME
RUN yes $USER_PASSWORD | passwd $USER_NAME

# set uid and gid to match those outside the container
RUN usermod -u $USER_ID $USER_NAME
RUN groupmod -g $USER_GID $USER_NAME

WORKDIR /home/$USER_NAME
# require no sudo pw in docker
RUN echo $USER_PASSWORD | sudo -S bash -c 'echo "'$USER_NAME' ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/docker-user' && printf "\n"

# Install some packages which are convenient for interactive shells
RUN apt update
RUN apt install -y iptables less vim ccache iproute2 tcpdump git iputils-ping ffmpeg

COPY spartan /home/$USER_NAME/spartan
COPY iiwa-tools /home/$USER_NAME/iiwa-tools

RUN git -C spartan submodule init
RUN git -C spartan submodule update drake director signal-scope
RUN yes "Y" | /home/$USER_NAME/spartan/setup/docker/install_dependencies.sh
RUN yes "Y" | /home/$USER_NAME/spartan/setup/ubuntu/16.04/install_prereqs_base.sh
RUN yes "Y" | /home/$USER_NAME/spartan/drake/setup/ubuntu/16.04/install_prereqs.sh

RUN chown $USER_ID:$USER_GID -R /home/$USER_NAME

ENTRYPOINT bash -c "source ~/spartan/setup/docker/entrypoint.sh && /bin/bash"
